### PR TITLE
Remove sections with information about datastores

### PR DESCRIPTION
**Pull request by e-zim**
### Type of change

- [ ] New sample
- [ ] New feature
- [ ] Bug fix
- [x] Documentation

### Summary

This PR removes sections in the README related to datastores, since this sample uses a Google Sheet as an external datastore instead of the Slack datastore.

### Requirements

- [x] I’ve checked my submission against the Samples Checklist to ensure it complies with all standards
- [x] I have ensured the changes I am contributing align with existing patterns and have tested and linted my code
- [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct)

### CODE REVIEW

**Review by misscoded — COMMENTED** [review]
I left these in all repos on purpose, namely so as folks build they know where to put things. What are your thoughts?

**Comment by e-zim** [comment]
@misscoded Ah I was unsure! Maybe there's a middle ground to explore? Perhaps we remove it from the `Project Structure` section but keep the informative section in the body?

If that sounds alright, I am also open to adding a line about this sample using Google Sheets as an alternative. But am also fine closing this PR altogether!

**Comment by misscoded** [comment]
Since all have been formatted like this, I'd prefer to close this and leave it as is for the time being. We can revisit once we do the pivot on the whole samples narrative!

**Comment by e-zim** [comment]
Makes sense and sounds like a plan!

**Pull request closed without merging**
